### PR TITLE
Update to use cloudCost by default

### PR DESCRIPTION
**Pull request by linhlam-kc**
Update to use cloudCost by default

### CODE REVIEW

**Review by srpomeroy — APPROVED** [review]
This looks good to me based on what I've heard/seen. I am interested in @kc-adawson feedback based on his experience. Anything else we should be changing with the move to the new API?

**Comment by linhlam-kc** [comment]
Thank you Sean ! I made changes based on our google doc at https://docs.google.com/document/d/1woTJKoFpBcEzVKpb0FzTeD5d1z9I9_EpTDqMYUtBtb4/edit . We may consider to add optional items as well, but I want to remove them for now to keep our Values file clean.

@kc-adawson Please feel free to share any feedback

**Comment by jessegoodier** [comment]
good to merge?

**Comment by linhlam-kc** [comment]
I go ahead and merge it as it matches with our doc, we can totally make another update if anything need to change.

**Pull request merged**
